version: '3'
services:
    rabbitmq:
        image: rabbitmq:3.8.9-management
        container_name: rabbitmq
        volumes:
            - $PWD/rabbitmq/data/:/var/lib/rabbitmq/
        environment:
            RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
            RABBITMQ_DEFAULT_USER: "admin"
            RABBITMQ_DEFAULT_PASS: "admin"
        ports:
            - "5672:5672"
            - "15672:15672"


#  Crear las carpetas de  mkdir rabbitmq
#  Dar permisos a las carpetas chmod a+rwx -R rabbitmq/data